vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - jpoissonnier.vscode-styled-components
ports:
- port: 3000
  onOpen: open-preview
tasks:
- init: >
    yarn install
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
