version: '3'
services:
  site:
    # Comment the image and uncomment the build fragment if you would like to build and run it locally.
    image: 'ghcr.io/dadosjusbr/site:main'
    #build:
    #  context: '.'
    env_file:
      - .env
    ports:
      - 80:8080
