// eslint-disable-next-line no-shadow
enum STATE_AGENCIES {
  //  ACRE = 'AC',
  ALAGOAS = 'AL',
  //  AMAPÁ = 'AP',
  //  AMAZONAS = 'AM',
  BAHIA = 'BA',
  CEARÁ = 'CE',
  ESPÍRITO_SANTO = 'ES',
  //  GOIÁS = 'GO',
  //  MARANHÃO = 'MA',
  //  MATO_GROSSO = 'MT',
  //  MATO_GROSSO_DO_SUL = 'MS',
  //  MINAS_GERAIS = 'MG',
  //  PARÁ = 'PA',
  PARAÍBA = 'PB',
  //  PARANÁ = 'PR',
  PERNAMBUCO = 'PE',
  PIAUÍ = 'PI',
  RIO_GRANDE_DO_NORTE = 'RN',
  RIO_GRANDE_DO_SUL = 'RS',
  //  RIO_DE_JANEIRO = 'RJ',
  //  RONDÔNIA = 'RO',
  //  RORAIMA = 'RR',
  SANTA_CATARINA = 'SC',
  //  SÃO_PAULO = 'SP',
  SERGIPE = 'SE',
  //  TOCANTINS = 'TO',
}
export default STATE_AGENCIES;
