name: Continuous Integration

on:
  pull_request:
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          if npm run build; then
            echo "Deployment succeeded✅"
          else
            echo "Deployment failed❌"
            exit 1
          fi
