name: Continuous Integration

on:
  pull_request:
jobs:
  building:
    runs-on: ubuntu-latest
    env:
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          if npm run build; then
            echo "Build succeeded✅"
          else
            echo "Build failed❌"
            exit 1
          fi
